# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'Getting started'
# Optionally set API keys here instead of exporting environment variables.
# Never commit real keys to source control.
env:
  GEMINI_API_KEY: AIzaSyDaFMprQosHRftQnRFWhbsHlaliTFw0ewI

prompts:
  - "./pronts.txt"

providers:
  - "google:gemini-2.5-pro"

concurrency: 1

tests:
  - "./variables_pronts/primeras_variables.yaml"
  - "./variables_pronts/secundas_variables.yaml"
